"""
A single service's whole timeline, past and future.

The dashboard shows one month at a time, which answers "what do I invoice this
month?" but not "did I ever invoice this contract in January?". This module
answers the second question: every occurrence of one service, in order, with
what happened to it.

It also surfaces something no other view can show. Occurrences are computed
from ``data_scadenza``, so when that anchor moves forward, the dates before it
stop being generated — but their state rows (billed, with the price frozen at
the time) stay in the database. Those rows ARE the billing history, and
without them the past would silently disappear from the page that exists to
show it. They are listed as entries with ``generata=False``.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.override_importo import OverrideImporto
from app.models.servizio import Servizio
from app.services.occorrenze import aggiungi_mesi, occorrenze_nel_periodo

# How far ahead to show for a contract that renews on its own: its occurrences
# never end, so the page needs a horizon. Two years is enough to see the next
# renewals without turning the page into an endless list.
MESI_FUTURI = 24


@dataclass
class VoceStorico:
    """One line of the timeline: an occurrence, or the trace one left behind."""

    data: date
    importo: Decimal
    quantita: int
    fatturato: bool
    stato_visivo: str
    apre_ciclo: bool
    da_override: bool
    note: str | None
    fatturato_il: object | None
    # False when the date is no longer generated by the engine and only its
    # state row survives — a billing that happened before the anchor moved.
    generata: bool

    @property
    def totale(self) -> Decimal:
        return self.importo * self.quantita


def storico_servizio(
    db: Session, servizio: Servizio, oggi: date | None = None
) -> list[VoceStorico]:
    """The service's timeline, oldest first."""
    oggi = oggi or date.today()
    stati = {
        riga.data_occorrenza: riga
        for riga in db.scalars(
            select(OverrideImporto).where(OverrideImporto.servizio_id == servizio.id)
        )
    }

    # Start from the earliest thing known about the service: the anchor, or an
    # older state row if the anchor has already moved past it.
    inizio = min([servizio.data_scadenza, *stati.keys()]) if stati else servizio.data_scadenza
    fine = aggiungi_mesi(max(oggi, servizio.data_scadenza), MESI_FUTURI)

    voci = []
    for occ in occorrenze_nel_periodo(servizio, inizio, fine, oggi=oggi):
        riga = stati.get(occ.data_occorrenza)
        voci.append(VoceStorico(
            data=occ.data_occorrenza,
            importo=occ.importo,
            quantita=occ.quantita,
            fatturato=occ.fatturato,
            stato_visivo=occ.stato_visivo,
            apre_ciclo=occ.apre_ciclo,
            da_override=occ.da_override,
            note=riga.note if riga else None,
            fatturato_il=riga.fatturato_il if riga else None,
            generata=True,
        ))

    generate = {v.data for v in voci}
    for data, riga in stati.items():
        if data in generate:
            continue
        voci.append(VoceStorico(
            data=data,
            # The frozen price if there is one, the service's own otherwise.
            importo=riga.importo if riga.importo is not None else servizio.importo,
            quantita=riga.quantita if riga.quantita is not None else servizio.quantita,
            fatturato=riga.fatturato,
            stato_visivo="fatturato" if riga.fatturato else "normale",
            apre_ciclo=True,
            da_override=riga.override_manuale,
            note=riga.note,
            fatturato_il=riga.fatturato_il,
            generata=False,
        ))

    voci.sort(key=lambda v: v.data)
    return voci
