"""add rinnovo_automatico and rinnovo_log

Revision ID: cb51cbcf2d89
Revises: adc2dc80492c
Create Date: 2026-06-15 17:43:54.079275+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb51cbcf2d89'
down_revision: Union[str, None] = 'adc2dc80492c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rinnovo_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servizio_id', sa.Integer(), nullable=False),
    sa.Column('data_rinnovo', sa.Date(), nullable=False),
    sa.Column('nuova_scadenza', sa.Date(), nullable=False),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.Column('totale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['servizio_id'], ['servizi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('servizi', sa.Column('rinnovo_automatico', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servizi', 'rinnovo_automatico')
    op.drop_table('rinnovo_log')
    # ### end Alembic commands ###
