"""initial schema

Revision ID: adc2dc80492c
Revises: 
Create Date: 2026-06-15 14:52:34.845871+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc2dc80492c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clienti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ruolo', sa.Enum('admin', 'utente', name='ruoloutente', native_enum=False, length=20), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utenti_username'), 'utenti', ['username'], unique=True)
    op.create_table('servizi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.Enum('licenza', 'contratto', 'abbonamento', 'altro', name='tiposervizio', native_enum=False, length=20), nullable=False),
    sa.Column('data_scadenza', sa.Date(), nullable=False),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.Column('valuta', sa.String(length=3), nullable=False),
    sa.Column('ricorrenza', sa.Enum('annuale', 'mensile', 'una_tantum', name='ricorrenza', native_enum=False, length=20), nullable=False),
    sa.Column('preavviso_giorni', sa.Integer(), nullable=False),
    sa.Column('stato', sa.Enum('attivo', 'scaduto', 'rinnovato', 'disdetto', name='statoservizio', native_enum=False, length=20), nullable=False),
    sa.Column('referente', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifica_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servizio_id', sa.Integer(), nullable=False),
    sa.Column('canale', sa.Enum('telegram', name='canalnotifica', native_enum=False, length=30), nullable=False),
    sa.Column('inviata_il', sa.DateTime(timezone=True), nullable=False),
    sa.Column('esito', sa.Boolean(), nullable=False),
    sa.Column('dettaglio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['servizio_id'], ['servizi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifica_log')
    op.drop_table('servizi')
    op.drop_index(op.f('ix_utenti_username'), table_name='utenti')
    op.drop_table('utenti')
    op.drop_table('clienti')
    # ### end Alembic commands ###
